# General spool config
spool.context.maindir=/tmp/spool-contexts

# Manifest options
spool.loader.log_level=error
spool.loader.log_file=loader.log
spool.stack.size=2M
spool.brk.size=512M
spool.fds.limit=4096
spool.enable.sigterm=true
spool.disable.aslr=false
spool.disallow.subprocesses=false
spool.sgx.edmm.enable=true
spool.sgx.max_threads=256

spool.arch_libdir=/lib/x86_64-linux-gnu
spool.entrypoint=/usr/lib/jvm/java-11-openjdk-amd64/bin/java
spool.fds_limit=1024
spool.sgx_enclave_size=4G
spool.sgx_edmm_enable=true
